# Generated by Django 4.1.3 on 2022-11-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_customer_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
